### ISSUE TITLE
Repository Handling

### ISSUE THREAD

**Issue by darksheer** [SUSE/sle2docker#12]
Has there been an consideration on a more 'elegant' way to handle repositories for docker images?  I know the XML must be edited, but manually sorting out the repos requires some heavy editing prior to build.  

One good example is that the Web Scripting Repo must be enabled if the user is wanting to install PHP--which manually has to be configured. 

A possible solutions:
XML generation based on entitlements of the host system? 
Command line arguments in sle2docker for REPO ID's / names?

**Comment by flavio** [comment]
The purpose of sle2docker is to allow customers to have basic SLE image that can be later customized using Docker's integrated build system.

We are also going to remove the whole building process, and hence also the XML files, in a couple of weeks. We are going to provide pre-built docker images that are going to be activated by sle2docker. 

The pre-built docker images are going to be distributed as RPMs inside of traditional repository. They are going to be installed by using zypper and then activated using sle2docker. This method makes the initial setup extremely fast.

Stay tuned for more news about that.

**Comment by darksheer** [comment]
Great!  Figured you guys had something cooking.  Is this going to be something within SLES 12 or just in OpenSUSE?

**Comment by flavio** [comment]
This is something affecting only SLE. openSUSE images are already published
on the Docker Hub.
