### ISSUE TITLE
What about image sizes after rpm updates if only prebuild images are available?

### ISSUE THREAD

**Issue by holgerreif** [SUSE/sle2docker#13]
If only prebuilt images are distributed then necessary package updates on the above layer will unnecessaryly grow the image size because space is required for both the old package content (in the distributed ancestor image) and the new custom layer.

How can this be addressed?

**Comment by mattiasgiese** [comment]
You may export the updated layer as a new image with only one layer.
Take a look at 'docker export'.

**Comment by flavio** [comment]
We automatically build the whole image using our internal instance of the Open Build Service. This produces a new Docker image that shares no layer with the previous version. The updated image is not going to include the old versions of the packages affected by the update, hence the disk size is not going to grow over the time.

You will have just to rebuild your custom docker image by pointing it to the new version of our base image.

You can remove the versions of your images based on the older release when you do not need them any more. This on the long run will save you disk space: you won't have to keep image v1, v2, v(n-1), v(n) on your machine all the time.
