### ISSUE TITLE
Adding Additional Repo's in Docker Image build with sle2docker

### ISSUE THREAD

**Issue by darksheer** [SUSE/sle2docker#15]
I have a number of repos available on the SLES12 host, but they aren't visible inside the container.  I tried adding the repos manually via zypper ar -r <path>, but its removed the next time zypper is ran.

Thanks in advance.

**Comment by flavio** [comment]
All our pre-built images have a zypper service that exposes the right repositories into the running container. You can fine more details about that on [this](https://www.suse.com/documentation/sles-12/dockerquick/data/dockerquick.html#sec_docker_sle_images_customizing_the_images) section of the documentation.

However you can keep adding repositories with `zypper ar`. How did you do that operation: via Dockerfile or from an interactive session inside of a container? In the latter case you have to commit your changes back to a new image to make them persistent.

**Comment by darksheer** [comment]
@flavio I did add the repo's via zypper ar and pointing to a copy of a .repo file from the host system.  Zypper immediately removed it at next run time. 

Is that not an acceptable method?

**Comment by flavio** [comment]
Yes it is. However you didn't answer my previous question:

> How did you do that operation: via Dockerfile or from an interactive session inside of a container? In the latter case you have to commit your changes back to a new image to make them persistent.

**Comment by flavio** [comment]
Closing: not an issue of sle2docker, plus no response so far. Feel free to comment further if needed.
