### ISSUE TITLE
Problem retrieving the repository index file for service 'container-suseconnect'

### ISSUE THREAD

**Issue by urban-it-solutions** [SUSE/sle2docker#17]
When I start zypper in the activated Image, I get the following error:

Refreshing service 'container-suseconnect'.
Problem retrieving the repository index file for service 'container-suseconnect':
[container-suseconnect|file:/usr/lib/zypp/plugins/services/container-suseconnect]
Warning: Skipping service 'container-suseconnect' because of the above error.
All services have been refreshed.
Warning: There are no enabled repositories defined.
Use 'zypper addrepo' or 'zypper modifyrepo' commands to add or enable repositories.

sle2docker-0.4.2-14.3.x86_64

Image:

    sles12-docker.x86_64-1.1.0-Build10.1

Seems like the SCCcredentials is not injected into the image. When I create a new one with the following Dockerfile-Command:

ADD SCCcredentials /etc/zypp/credentials.d/

It works....

**Comment by flavio** [comment]
Which version of Docker are you running? Is the host a SLE machine?

**Comment by urban-it-solutions** [comment]
Docker version 1.9.1, build a34a1d5

Host is SLES12

**Comment by flavio** [comment]
I guess you are taking this file from OBS://Virtualization/containers. This docker daemon has not the patches required to inject the credentials. That's why this is not working.

In the meantime you have to use the workaround you mentioned (`ADD SCCcredentials ...`)
