### ISSUE TITLE
Add an "all" subcommand or option to the `activate` command

### ISSUE THREAD

**Issue by mssola** [SUSE/sle2docker#18]
When testing SLE images, you might want to test them all, and it can be a bit frustrating to call `activate`for each of them. Therefore, I propose to include a subcommand or a flag like this:

    $ sle2docker activate all

or

    $ sle2docker activate --all

**Comment by darksheer** [comment]
+1 to his suggestion.

**Comment by flavio** [comment]
I agree, let's work on that

**Comment by eotchi** [comment]
As already mentioned to @mssola, this definitely makes senses. Tracked and added to the backlog.
